title: Abdelah El Harsal â€“ Portfolio
description: Portfolio personnel
theme: null
baseurl: "/portfolio" 
url: "https://abdel95j.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
